---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/markewq4/wb.marketsculpt.com/
    - /bin/cp -R index.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R deploy.php $DEPLOYPATH
    - /bin/cp -R api.php $DEPLOYPATH
    - /bin/cp -R setup_db.php $DEPLOYPATH
